       void cdft(int n, int isgn, double *a, int *ip, double *w);
static void rdft(int n, int isgn, double *a, int *ip, double *w);
static void ddct(int n, int isgn, double *a, int *ip, double *w);
static void ddst(int n, int isgn, double *a, int *ip, double *w);
static void dfct(int n, double *a, double *t, int *ip, double *w);
static void dfst(int n, double *a, double *t, int *ip, double *w);
static void makewt(int nw, int *ip, double *w);
static void makeipt(int nw, int *ip);
static void makect(int nc, int *ip, double *c);
static void cftfsub(int n, double *a, int *ip, int nw, double *w);
static void cftbsub(int n, double *a, int *ip, int nw, double *w);
static void bitrv2(int n, int *ip, double *a);
static void bitrv2conj(int n, int *ip, double *a);
static void bitrv216(double *a);
static void bitrv216neg(double *a);
static void bitrv208(double *a);
static void bitrv208neg(double *a);
static void cftf1st(int n, double *a, double *w);
static void cftb1st(int n, double *a, double *w);
static void cftrec4_th(int n, double *a, int nw, double *w);
static void *cftrec1_th(void *p);
static void *cftrec2_th(void *p);
static void cftrec4(int n, double *a, int nw, double *w);
static int cfttree(int n, int j, int k, double *a, int nw, double *w);
static void cftleaf(int n, int isplt, double *a, int nw, double *w);
static void cftmdl1(int n, double *a, double *w);
static void cftmdl2(int n, double *a, double *w);
static void cftfx41(int n, double *a, int nw, double *w);
static void cftf161(double *a, double *w);
static void cftf162(double *a, double *w);
static void cftf081(double *a, double *w);
static void cftf082(double *a, double *w);
static void cftf040(double *a);
static void cftb040(double *a);
static void cftx020(double *a);
static void rftfsub(int n, double *a, int nc, double *c);
static void rftbsub(int n, double *a, int nc, double *c);
static void dctsub(int n, double *a, int nc, double *c);
static void dstsub(int n, double *a, int nc, double *c);
